// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAEtQdm5dFOGSqaFFbOjv8Zm6VYH4p7N8',
    appId: '1:788675984880:android:aa961cc9ca2aedeed83135',
    messagingSenderId: '788675984880',
    projectId: 'uff1-asqp6a',
    storageBucket: 'uff1-asqp6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKvYhjEKJEZiO7iC-EPkWDth-tyEtSZVg',
    appId: '1:788675984880:ios:176d263cd3b99bc4d83135',
    messagingSenderId: '788675984880',
    projectId: 'uff1-asqp6a',
    storageBucket: 'uff1-asqp6a.appspot.com',
    androidClientId: '788675984880-q7ljhlovom5bld3bc54ur1qpkqetva20.apps.googleusercontent.com',
    iosClientId: '788675984880-n84a39uva06r2qsikpmguvo1pgevhk3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodForYou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKvYhjEKJEZiO7iC-EPkWDth-tyEtSZVg',
    appId: '1:788675984880:ios:24f04dcec0c44ef5d83135',
    messagingSenderId: '788675984880',
    projectId: 'uff1-asqp6a',
    storageBucket: 'uff1-asqp6a.appspot.com',
    androidClientId: '788675984880-q7ljhlovom5bld3bc54ur1qpkqetva20.apps.googleusercontent.com',
    iosClientId: '788675984880-u4b7it60v9js5sqdtju1en0ai6kopn6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodForYou.RunnerTests',
  );
}
